### PR TITLE
fix(test): update the zot tests not to use test/data as rootDir (use …

### LINKED ISSUE #1160: Update the zot tests not to use test/data as rootDir (use a temporary folder instead)

### PR DESCRIPTION
**Pull request by nicoldr**
…a temporary folder instead)
- Use testing's TempDir() to create temporary directories intead of os.MkdirTemp()

Signed-off-by: Nicol Draghici <idraghic@cisco.com>

**What type of PR is this?**

**Which issue does this PR fix**:
Closes #1160 

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/common/common_test.go [hunk 1]
```diff
@@ -42,6 +42,8 @@ func TestCommon(t *testing.T) {
 	Convey("test dirExists()", t, func() {
 		exists := common.DirExists("testdir")
 		So(exists, ShouldBeFalse)
+		tempDir := t.TempDir()
+		test.CopyTestFiles("../../test/data", tempDir)
 
 		file, err := os.Create("file.txt")
```
Comment (andaaron) [inline pkg/common/common_test.go:48]: I guess the file should be created under tempDir. By why copy the other files at line 46?

File: pkg/extensions/search/cve/cve_test.go [hunk 2]
```diff
@@ -373,8 +373,6 @@ func TestImageFormat(t *testing.T) {
 
 func TestCVESearchDisabled(t *testing.T) {
 	Convey("Test with CVE search disabled", t, func() {
-		dbDir := testDir
```
Comment (andaaron) [inline pkg/extensions/search/cve/cve_test.go:376]: Can the global testDir be removed as well?

**Review by andaaron — APPROVED** [review]

**Review by rchincha — APPROVED** [review]
lgtm
