### PR TITLE
graphql: Apply authorization on /_search endpoint

### LINKED ISSUE #615: graphql: Apply authorization on /_search endpoint
**Describe the bug**
Apply authorization for _search endpoint (graphql)

Currently authorization is applied only for dist-spec routes and not for graphql.

On a request context we store the repositories on which a user has read access, and later used them when the user GETs the catalog for example, to filter out the repos on which he doesn't have access.

Do the same for _search endpoint.

### PR DESCRIPTION
**Pull request by alexstan12**
- AccessControlContext now resides in a separate package from where it can be imported,
along with the contextKey that will be used to set and retrieve this context value.

- AccessControlContext has a new field called Username, that will be of use for future
implementations in graphQL resolvers.

- GlobalSearch resolver now uses this context to filter repos available to the logged user.

Closes #615

**What type of PR is this?**
feature

**Which issue does this PR fix**:
using authz context for use on GraphQl resolvers

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/context/context.go [hunk 1]
```diff
@@ -0,0 +1,18 @@
+package context
```
Comment (peusebiu) [inline pkg/context/context.go:1]: I don't like the naming of this, it gets confusing.

**Comment by peusebiu** [comment]
lgtm

File: pkg/context/context.go (hunk 1 above)
Comment (alexstan12) [reply pkg/context/context.go:1]: what about userContext? if this file will gather over time all types of contexts useful to zot, maybe just zotContext ?

Comment (peusebiu) [reply pkg/context/context.go:1]: I would say requestContext or reqContext.

Comment (alexstan12) [reply pkg/context/context.go]: package renamed to requestcontext .

File: pkg/api/controller_test.go [hunk 2]
```diff
@@ -5147,6 +5146,138 @@ func TestPeriodicTasks(t *testing.T) {
...
+			ctlr.Config.Storage.RootDirectory = tempDir
+
+			go startServer(ctlr)
+			defer stopServer(ctlr)
+			test.WaitTillServerReady(baseURL)
+
+			query := `
+			{
+				GlobalSearch(query:""){
+					Repos {
```
Comment (andaaron) [inline pkg/api/controller_test.go:5236]: I think we should have a test according to which we verify that one repo is returned because the user has permissions to view it, while another is not returned as the user doesn't have permissions to view the second one.

**Review by andaaron — COMMENTED** [review]
Looks good overall.

**Review by andaaron — DISMISSED** [review]

**Review by andaaron — APPROVED** [review]

**Review by andaaron — APPROVED** [review]

**Review by peusebiu — APPROVED** [review]
LGTM

File: pkg/api/authz.go [hunk 3]
```diff
@@ -213,6 +208,12 @@ func AuthzHandler(ctlr *Controller) mux.MiddlewareFunc {
 				return
 			}
 
+			if strings.Contains(request.RequestURI, constants.ExtSearchPrefix) {
+				next.ServeHTTP(response, request.WithContext(ctx))
```
Comment (rchincha) [inline pkg/api/authz.go:212]: Why are we not falling back to the normal path below?

Comment (rchincha) [reply pkg/api/authz.go:212]: And what is the "next" handler?

**Review by rchincha — COMMENTED** [review]
Just some clarifications, the PR looks ok

File: pkg/api/authz.go (hunk 3 above)
Comment (alexstan12) [reply pkg/api/authz.go:212]: We are not falling back on the normal path because on line [239](https://github.com/project-zot/zot/pull/728/files/7517df3258d350ac53c0d84be6d91f02f6575aed#diff-fa881d434bc95a6195440f2122784dacca2bcbc19b93baf9e575feed1265340aL239) the "resource" variable will be empty, since this in a request variable for REST API calls. Thus authz will fail - line 241.

Comment (alexstan12) [reply pkg/api/authz.go:212]: > And what is the "next" handler?

idk what do you mean by this, nothing has changed in this approach. 
```func(next http.Handler) http.Handler``` is the signature of a MiddlewareFunc, and in our case the "next" handler will be the router inside the Controller.
We serve back the incoming http requests with modified context ```next.ServeHTTP(response, request.WithContext(ctx))```

**Review by andaaron — APPROVED** [review]
