### PR TITLE
sync: periodically retry if on-demand fails inline, closes #281

### LINKED ISSUE #281: sync: periodically retry if on-demand fails inline
Noticing that once dockerhub limits inside a org are maxed, then subsequent pulls likely to fail.
Instead, given that dockerhub doesn't allow image search, can we just post a future task to pull again periodically (be good netizens though)

### PR DESCRIPTION
**Pull request by peusebiu**
Signed-off-by: Petu Eusebiu <peusebiu@cisco.com>

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/extensions/sync/sync_test.go [hunk 1]
```diff
@@ -2227,7 +2459,7 @@ func TestSyncSignaturesOnDemand(t *testing.T) {
 		// sync on demand
 		resp, err = resty.R().Get(destBaseURL + "/v2/" + repoName + "/manifests/1.0")
 		So(err, ShouldBeNil)
-		So(resp.StatusCode(), ShouldEqual, 404)
+		So(resp.StatusCode(), ShouldEqual, 200)
```
Comment (peusebiu) [inline pkg/extensions/sync/sync_test.go:2462]: Had to change it, sync signatures won't return error anymore, because the image was successfully synced already and next time we will request it it will work, but the signature won't be there, so either the signature is not on the upstream or there was a temporary error and we will get it eventually.

File: pkg/extensions/sync/sync.go [hunk 2]
```diff
@@ -494,8 +496,7 @@ func Run(cfg Config, storeController storage.StoreController, wtgrp *goSync.Wait
 
 				if err := syncRegistry(regCfg, storeController, logger, localCtx, policyCtx,
 					credentialsFile[upstreamRegistry], uuid.String()); err != nil {
-					logger.Error().Err(err).Msg("sync exited with error, stopping it...")
-					ticker.Stop()
```
Comment (peusebiu) [inline pkg/extensions/sync/sync.go:498]: Don't stop the ticker anymore since retry options can be configured.
Keep retrying on PollIntervals

**Comment by peusebiu** [comment]
Added:
sync: don't return error on sync signatures, just skip them, closes project-zot#375

File: examples/README.md [hunk 3]
```diff
@@ -421,7 +421,9 @@ Configure each registry sync:
 			{
 				"url": "https://docker.io/library",
 				"onDemand": true,                   # doesn't have content, don't periodically pull, pull just on demand.
-				"tlsVerify": true
+				"tlsVerify": true,
+        "maxRetry": 3,                      # optionally you can specify maxRetry and the delay between retries for each
```
Comment (rchincha) [inline examples/README.md:425]: "maxRetries"

File: examples/README.md [hunk 4]
```diff
@@ -421,7 +421,9 @@ Configure each registry sync:
...
+        "delay": "15m"                      # registry config, it's applied for both on demand and periodically syncing.
```
Comment (rchincha) [inline examples/README.md:426]: "retryDelay"

**Review by rchincha — COMMENTED** [review]
Add an example in some examples/config* file

File: pkg/extensions/sync/on_demand.go [hunk 5]
```diff
@@ -70,101 +87,157 @@ func OneImage(cfg Config, storeController storage.StoreController,
...
+					or retryOptions is not configured */
+					continue
+				}
+
+				// spawn goroutine to later pull the image
+				go func() {
+					// remove image after syncing
+					defer os.RemoveAll(localCachePath)
+					defer demandedImgs.Delete(demandedImageRef)
+
```
Comment (rchincha) [inline pkg/extensions/sync/on_demand.go:191]: Add a "defer" log msg indicating when this goroutine exited

File: pkg/extensions/sync/on_demand.go [hunk 6]
```diff
@@ -3,29 +3,51 @@ package sync
...
 func OneImage(cfg Config, storeController storage.StoreController,
-	repo, tag string, log log.Logger) error {
-	var credentialsFile CredentialsFile
+	repo, tag string, isArtifact bool, log log.Logger) error {
+	// guard against multiple parallel requests
+	demandedImage := fmt.Sprintf("%s:%s", repo, tag)
+	// loadOrStore image-based channel
+	value, found := demandedImgs.LoadOrStore(demandedImage, make(chan error))
+	imageChannel, _ := value.(chan error)
```
Comment (rchincha) [inline pkg/extensions/sync/on_demand.go:31]: why typecast, just return a proper type from LoadOrStore, or change the API signatures, no multipurpose stuff pls.

Comment (peusebiu) [reply pkg/extensions/sync/on_demand.go]: this is how sync.Map works :d, I made a wrapper around it.

**Review by rchincha — APPROVED** [review]
lgtm
